// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvJ2XC-qUS1s2vWvPplB3rKFQOZRY1MYI',
    appId: '1:477012757677:web:14fca0443a3b3270d48a24',
    messagingSenderId: '477012757677',
    projectId: 'fleet-goal-372106',
    authDomain: 'fleet-goal-372106.firebaseapp.com',
    storageBucket: 'fleet-goal-372106.appspot.com',
    measurementId: 'G-F13LRQ113M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoOikpWBI5JyRAyY8tZPoObdEsaH4Sfo4',
    appId: '1:477012757677:android:70d503ef053aedcdd48a24',
    messagingSenderId: '477012757677',
    projectId: 'fleet-goal-372106',
    storageBucket: 'fleet-goal-372106.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDONpWSoJdfZq5PgMQM-yR4h4Vc5CixNbY',
    appId: '1:477012757677:ios:038e89979ce904bed48a24',
    messagingSenderId: '477012757677',
    projectId: 'fleet-goal-372106',
    storageBucket: 'fleet-goal-372106.appspot.com',
    iosClientId: '477012757677-qqn56lm29bguadoif3v73l03sfrovp2b.apps.googleusercontent.com',
    iosBundleId: 'com.example.withesWebapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDONpWSoJdfZq5PgMQM-yR4h4Vc5CixNbY',
    appId: '1:477012757677:ios:038e89979ce904bed48a24',
    messagingSenderId: '477012757677',
    projectId: 'fleet-goal-372106',
    storageBucket: 'fleet-goal-372106.appspot.com',
    iosClientId: '477012757677-qqn56lm29bguadoif3v73l03sfrovp2b.apps.googleusercontent.com',
    iosBundleId: 'com.example.withesWebapp',
  );
}
