// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlXsOdH-AkzhxQ3V1c_wzhNQQS7fFk2aI',
    appId: '1:800751398617:web:95e7015300b02ccdc158c8',
    messagingSenderId: '800751398617',
    projectId: 'convenience-delivered-app',
    authDomain: 'convenience-delivered-app.firebaseapp.com',
    storageBucket: 'convenience-delivered-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChXrTis03IkoQQQkI-8IsHYJ_43LjjmyU',
    appId: '1:800751398617:android:3a7273a7d8607cfec158c8',
    messagingSenderId: '800751398617',
    projectId: 'convenience-delivered-app',
    storageBucket: 'convenience-delivered-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPiZnMUpc-2DUExFJh63rB7JmEznQ2guk',
    appId: '1:800751398617:ios:1518e2ad89bc9688c158c8',
    messagingSenderId: '800751398617',
    projectId: 'convenience-delivered-app',
    storageBucket: 'convenience-delivered-app.appspot.com',
    iosClientId: '800751398617-26aberhrg419gk4kc0tmukuchq218hm6.apps.googleusercontent.com',
    iosBundleId: 'com.example.withesWebapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPiZnMUpc-2DUExFJh63rB7JmEznQ2guk',
    appId: '1:800751398617:ios:1518e2ad89bc9688c158c8',
    messagingSenderId: '800751398617',
    projectId: 'convenience-delivered-app',
    storageBucket: 'convenience-delivered-app.appspot.com',
    iosClientId: '800751398617-26aberhrg419gk4kc0tmukuchq218hm6.apps.googleusercontent.com',
    iosBundleId: 'com.example.withesWebapp',
  );
}
